### PR TITLE
Support rendering more than one level of components.

### PR DESCRIPTION
**Pull request by Gongreg**
Rewritten parsing of story component. Properly renders multiple levels deep (it used to crash).
Only passed props are rendered (skips default value props).

### CODE REVIEW

**Comment by simply-innovative** [comment]
@mthuret: can you please accept this merge request since in current version rendering more than one level of components are not supported. 

thanks in advance and looking forward for a version with the fixed patch

**Comment by Gongreg** [comment]
@simply-innovative I am creating a new npm module for it, give me two hours and I will ping you.

**Comment by Gongreg** [comment]
@simply-innovative New npm package is here: https://www.npmjs.com/package/storybook-usage.

mthuret: I've added you into credits, saying that you were the author.

Closing the pr now.

**Comment by simply-innovative** [comment]
Many many thanks @Gongreg for creating npm package with the fix.

**Comment by mthuret** [comment]
@Gongreg @simply-innovative : sorry for that, for a reason I wasn't notify of the activity on this repo. 
There's also this package I found really nice => https://github.com/Kilix/storybook-addon-jsx

**Pull request closed without merging**
